const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"考勤状态管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKaoqinxiangqingStatus"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"课程类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"请假类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueshengqingjia"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"专业管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhuanye"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"辅导员管理",
                        "menuJump":"列表",
                        "tableName":"fudaoyuan"
                    }
                ],
                "menu":"辅导员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshi"
                    }
                ],
                "menu":"教师管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"院系考勤管理员管理",
			            "menuJump":"列表",
			            "tableName":"kaoqinguanli"
			        }
			    ],
			    "menu":"院系考勤管理员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"课程信息管理",
			            "menuJump":"列表",
			            "tableName":"kecheng"
			        }
			    ],
			    "menu":"课程信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
							"报表"
                        ],
                        "menu":"考勤通知管理",
                        "menuJump":"列表",
                        "tableName":"kaoqin"
                    }
                ],
                "menu":"考勤通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"考勤详情管理",
                        "menuJump":"列表",
                        "tableName":"kaoqinxiangqing"
                    }
                ],
                "menu":"考勤详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"学生请假管理",
                        "menuJump":"列表",
                        "tableName":"xueshengqingjia"
                    }
                ],
                "menu":"学生请假管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
			                "查看",
			                "新增",
			                "删除",
							"报表"
	                    ],
	                    "menu":"考勤通知管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqin"
	                }
	            ],
	            "menu":"考勤通知管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"考勤详情管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqinxiangqing"
	                }
	            ],
	            "menu":"考勤详情管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"学生请假管理",
	                    "menuJump":"列表",
	                    "tableName":"xueshengqingjia"
	                }
	            ],
	            "menu":"学生请假管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"辅导员",
	    "tableName":"fudaoyuan"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"课程信息管理",
			            "menuJump":"列表",
			            "tableName":"kecheng"
			        }
			    ],
			    "menu":"课程信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
			                "查看",
			                "新增",
			                "删除",
							"报表"
	                    ],
	                    "menu":"考勤通知管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqin"
	                }
	            ],
	            "menu":"考勤通知管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"考勤详情管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqinxiangqing"
	                }
	            ],
	            "menu":"考勤详情管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"院系考勤管理员",
	    "tableName":"kaoqinguanli"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
                            "查看",
                            "新增",
                            "删除",
			            ],
			            "menu":"课程信息管理",
			            "menuJump":"列表",
			            "tableName":"kecheng"
			        }
			    ],
			    "menu":"课程信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
                            "查看",
                            "新增",
                            "删除",
							"报表"
	                    ],
	                    "menu":"考勤通知管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqin"
	                }
	            ],
	            "menu":"考勤通知管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"考勤详情管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqinxiangqing"
	                }
	            ],
	            "menu":"考勤详情管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"课程信息管理",
			            "menuJump":"列表",
			            "tableName":"kecheng"
			        }
			    ],
			    "menu":"课程信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"考勤通知管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqin"
	                }
	            ],
	            "menu":"考勤通知管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"考勤"
	                    ],
	                    "menu":"待考勤考勤信息",
	                    "menuJump":"列表",
	                    "tableName":"kaoqinxiangqing"
	                }
	            ],
	            "menu":"待考勤考勤信息"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
							"删除"
	                    ],
	                    "menu":"请假管理",
	                    "menuJump":"列表",
	                    "tableName":"xueshengqingjia"
	                }
	            ],
	            "menu":"请假管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"学生",
	    "tableName":"yonghu"
	},
]
    }
}
export default menu;
